server:
  port: 8080
  servlet:
    context-path: /api

spring:
  application:
    name: travel-assistant-backend
  jackson:
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false

# Azure OpenAI Configuration
azure:
  openai:
    endpoint: https://hackathon-openui-test.openai.azure.com
    api-key: B4kxaCF6fe7KnBbRsDhk8EZZhvAz7MdVPXab3qJzZbahvpctLIT5JQQJ99BCAC77bzfXJ3w3AAABACOGTN88
    deployment-name: gpt-4o
    api-version: 2025-01-01-preview
    max-tokens: 4096
    temperature: 0.7

# CORS Configuration
cors:
  allowed-origins: 
    - "http://localhost:5173"
    - "http://localhost:3000"
    - "http://localhost:3001"
    - "http://localhost:3002"
    - "http://localhost:3003"
    - "http://localhost:3004"
    - "http://localhost:3005"
    - "http://localhost:3006"
    - "http://127.0.0.1:5173"
    - "http://127.0.0.1:3000"
    - "http://127.0.0.1:3001"
    - "http://127.0.0.1:3002"
    - "http://127.0.0.1:3003"
    - "http://127.0.0.1:3004"
    - "http://127.0.0.1:3005"
    - "http://127.0.0.1:3006"
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    com.ct.hackathon: DEBUG
    org.springframework.web: DEBUG
    org.springframework.webflux: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n" 